routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Artistas
Route::name('artistas.')->group(function () {

	Route::post('artistas/store', [
	    'as'   => 'store',
	    'uses' => 'ArtistasController@store',
	]);
	Route::get('artistas', [
	    'as'   => 'index',
	    'uses' => 'ArtistasController@index',
	]);
	Route::get('artistas/create', [
	    'as'   => 'create',
	    'uses' => 'ArtistasController@create',
	]);
	Route::get('artistas/destroy/{artista}', [
	    'as'   => 'destroy',
	    'uses' => 'ArtistasController@destroy',
	]);
	Route::post('artistas/{artista}', [
	    'as'   => 'update',
	    'uses' => 'ArtistasController@update',
	]);
	Route::get('artistas/{artista}/edit', [
	    'as'   => 'edit',
	    'uses' => 'ArtistasController@edit',
	]);
	Route::get('artistas/{artista}/show', [
	    'as'   => 'show',
	    'uses' => 'ArtistasController@show',
	]);

});

// Músicas
Route::name('musicas.')->group(function () {
	Route::post('musicas/store', [
	    'as'   => 'store',
	    'uses' => 'MusicasController@store',
	]);
	Route::get('musicas', [
	    'as'   => 'index',
	    'uses' => 'MusicasController@index',
	]);
	Route::get('musicas/artista/{artista}', [
	    'as'   => 'musicasArtista',
	    'uses' => 'MusicasController@musicasArtista',
	]);	
	Route::get('musicas/create', [
	    'as'   => 'create',
	    'uses' => 'MusicasController@create',
	]);
	Route::get('musicas/destroy/{musica}', [
	    'as'   => 'destroy',
	    'uses' => 'MusicasController@destroy',
	]);
	Route::post('musicas/{musica}', [
	    'as'   => 'update',
	    'uses' => 'MusicasController@update',
	]);
	Route::get('musicas/{musica}/edit', [
	    'as'   => 'edit',
	    'uses' => 'MusicasController@edit',
	]);
	Route::get('musicas/{musica}/show', [
	    'as'   => 'show',
	    'uses' => 'MusicasController@show',
	]);
});

app/Artistas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Request;

/**
 * @property int $id
 * @property mixed $nome
 * @property mixed $genero
 */
class Artistas extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'artistas';

    /**
     * @var array
     */
    protected $fillable = ['nome', 'genero', 'status'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function musicas()
    {
        return $this->hasMany('Musicas');
    }

    public function scopeAtivo($query) {

        $filter=Request::only($this->sortable);
        $query->where('status','=',true);

        return $query;
    }      

    /**
     * Scope to search for screen filters. 
     */
    public function scopeFilterSearch($query) {


        $filter=Request::only($this->sortable);

        if(!empty($filter['nome'])){
            $query->where("nome","LIKE","%{$filter['nome']}%");
        }

        if(!empty($filter['genero'])){
            $query->where('genero','=',$filter['genero']);
        }

        return $query;
    }
}

app/Http/Controllers/ArtistasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\ArtistasRequest;
use App\Artistas;

class ArtistasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return view
     */
    public function index(Request $request)
    {
    	$generos = config('enums.generos');
        $artistas = Artistas::filterSearch()
        	->ativo()
            ->paginate(config('default.pagination.max'));

        $artistas->appends(Input::except('page'));

        return view('artistas.index',compact('artistas', 'generos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return view
     */
    public function create()
    {
        $generos = config('enums.generos');
        return view('artistas.create', compact('generos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArtistasRequest $request)
    {
        $artista = new Artistas();
        
        $artista->fill($request->all());
        $artista->save();

        $success = __('Artista cadastrado com sucesso!');
        Session::flash('success',$success);

        return redirect()->route('artistas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Artista  $artista
     * @return \Illuminate\Http\Response
     */
    public function show(Artistas $artista)
    {
        return view('artistas.show',compact('artista'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Artista  $artista
     * @return \Illuminate\Http\Response
     */
    public function edit(Artistas $artista)
    {
		$generos = config('enums.generos');
        return view('artistas.edit',compact('artista', 'generos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Artistas $artista
     * @return \Illuminate\Http\Response
     */
    public function update(ArtistasRequest $request, Artistas $artista)
    {
        try {
			$artista->update($request->all());

        } catch (ModelNotFoundException $e) {
            $message = __('Houve um problema ao editar o artista.');
            Session::flash('error', $message);

            return redirect()->route('artistas.edit');
        }

        $message = __('Artista editado com sucesso.');
        Session::flash('success', $message);

        return redirect()->route('artistas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Artistas  $artistay
     * @return \Illuminate\Http\Response
     */
	public function destroy(Artistas $artista)
    {
        try {
			$artista->status = false;
			$artista->save();

        } catch (ModelNotFoundException $e) {
            $message = __('Houve um problema ao remover o artista.');
            Session::flash('error', $message);

            return redirect()->route('artistas.index');
        }

        $message = __('Artista removido com sucesso.');
        Session::flash('success', $message);

        return redirect()->route('artistas.index');
    }
}

resources/views/artistas/_form.blade.php
<div class="row mb-4 filters">
    <div class="col-md-4 col-12">
        <label for="nome">Nome <span class="text-danger">*</span></label>
        <input class="form-control" type="text" id="nome" maxlength="150" name="nome" value="{{@old('nome')??$artista->nome??''}}" required />
    </div>

    <div class="col-md-4 col-12">
        <label for="tipo">Gênero <span class="text-danger">*</span></label>
		<select class="form-control" name="genero" id="genero" required>

					
			@foreach($generos as $genero)
                @if(isset($artista) && $artista->genero == $genero)
                    <option value="{{$genero}}" selected="selected">{!! $genero !!}</option>
                @else
                    <option value="{{$genero}}">{!! $genero !!}</option>
                @endif
            @endforeach


        </select>        
    </div>
</div>

resources/views/artistas/create.blade.php
<form role="form" id="form_artistas" action="{{route('artistas.store')}}" method="post" >
{{csrf_field()}}
@include('artistas._form')
<div class="row">
    <div class="ml-3 mt-3">
		<button type="submit">Salvar</button>
    </div>
</div>    
</form>

resources/views/artistas/edit.blade.php
<form role="form" id="form_artistas" action="{{route('artistas.update', $artista)}}" method="post" >
{{csrf_field()}}
@include('artistas._form')
<div class="row">
    <div class="ml-3 mt-3">
		<button type="submit">&nbsp;</i> Salvar</button>
    </div>
</div>    
</form>

<a href="{{ route('artistas.index') }}">Voltar</a>

resources/views/artistas/index.blade.php
<h1>Artistas</h1>

@if (Session::has('success'))
	<p>{{ Session::get('success') }}</p>
@endif
@if (Session::has('error'))
	<strong>Erro: </strong><p>{{ Session::get('error') }}</p>
@endif

<p><a href="{{ route('artistas.create') }}">Adicionar</a></p>

<form role="form" id="form_filtro" action="{{route('artistas.index')}}" method="get" >
    <label for="nome">Nome <span class="text-danger">*</span></label>
    <input class="form-control" type="text" id="nome" maxlength="150" name="nome" value="{{Request::get('nome')}}" />

    <label for="tipo">Gênero <span class="text-danger">*</span></label>
	<select class="form-control" name="genero" id="genero">
		<option value="" selected="selected"></option>
		@foreach($generos as $genero)
            @if(Request::get('genero') && Request::get('genero') == $genero)
                <option value="{{$genero}}" selected="selected">{!! $genero !!}</option>
            @else
                <option value="{{$genero}}">{!! $genero !!}</option>
            @endif
        @endforeach
    </select> 
    <button type="submit">Filtrar</button>       
</form>



<table>
	<thead>
		<tr>
			<th>Nome</th>
			<th>Gênero</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		@foreach($artistas as $artista)
			<tr>
				<td>{{ $artista->nome }}</td>
				<td>{{ $artista->genero }}</td>
				<td>
					<a href="{{ route('artistas.show', $artista) }}">Ver</a>
					<a href="{{ route('artistas.edit', $artista) }}">Editar</a>
					<a href="{{ route('artistas.destroy', $artista) }}">Remover</a>
					<a href="{{ route('musicas.musicasArtista', $artista) }}">Músicas</a>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>

resources/views/artistas/show.blade.php
<h1>Artistas</h1>

<table>
	<thead>
		<tr>
			<th>Nome</th>
			<th>Gênero</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{ $artista->nome }}</td>
			<td>{{ $artista->genero }}</td>
		</tr>
	</tbody>
</table>

<a href="{{ route('artistas.index') }}">Voltar</a>