routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Artistas
Route::name('artistas.')->group(function () {

	Route::post('artistas/store', [
	    'as'   => 'store',
	    'uses' => 'ArtistasController@store',
	]);
	Route::get('artistas', [
	    'as'   => 'index',
	    'uses' => 'ArtistasController@index',
	]);
	Route::get('artistas/create', [
	    'as'   => 'create',
	    'uses' => 'ArtistasController@create',
	]);
	Route::get('artistas/destroy/{artista}', [
	    'as'   => 'destroy',
	    'uses' => 'ArtistasController@destroy',
	]);
	Route::post('artistas/{artista}', [
	    'as'   => 'update',
	    'uses' => 'ArtistasController@update',
	]);
	Route::get('artistas/{artista}/edit', [
	    'as'   => 'edit',
	    'uses' => 'ArtistasController@edit',
	]);
	Route::get('artistas/{artista}/show', [
	    'as'   => 'show',
	    'uses' => 'ArtistasController@show',
	]);

});

// Músicas
Route::name('musicas.')->group(function () {
	Route::post('musicas/store', [
	    'as'   => 'store',
	    'uses' => 'MusicasController@store',
	]);
	Route::get('musicas', [
	    'as'   => 'index',
	    'uses' => 'MusicasController@index',
	]);
	Route::get('musicas/artista/{artista}', [
	    'as'   => 'musicasArtista',
	    'uses' => 'MusicasController@musicasArtista',
	]);	
	Route::get('musicas/create', [
	    'as'   => 'create',
	    'uses' => 'MusicasController@create',
	]);
	Route::get('musicas/destroy/{musica}', [
	    'as'   => 'destroy',
	    'uses' => 'MusicasController@destroy',
	]);
	Route::post('musicas/{musica}', [
	    'as'   => 'update',
	    'uses' => 'MusicasController@update',
	]);
	Route::get('musicas/{musica}/edit', [
	    'as'   => 'edit',
	    'uses' => 'MusicasController@edit',
	]);
	Route::get('musicas/{musica}/show', [
	    'as'   => 'show',
	    'uses' => 'MusicasController@show',
	]);
});

app/Musicas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * @property int $id
 * @property int $artistas_id
 * @property mixed $nome
 * @property time $duracao
 */
class Musicas extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'musicas';

    /**
     * @var array
     */
    protected $fillable = ['artistas_id', 'nome', 'duracao'];

}

app/Http/Controllers/MusicasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use App\Http\Requests\MusicasRequest;
use App\Musicas;
use App\Artistas;

class MusicasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return view
     */
    public function index(Request $request)
    {
        $musicas = Musicas::select('musicas.*', 'artistas.nome as artista')
            ->join('artistas','musicas.artistas_id','=', 'artistas.id')
            ->paginate(config('default.pagination.max'));
        $musicas->appends(Input::except('page'));

        return view('musicas.index',compact('musicas'));
    }

    public function musicasArtista(Artistas $artista)
    {
        $musicas = Musicas::select('musicas.*', 'artistas.nome as artista')
            ->join('artistas','musicas.artistas_id','=', 'artistas.id')
            ->where('musicas.artistas_id', '=', $artista->id)
            ->paginate(config('default.pagination.max'));
        $musicas->appends(Input::except('page'));

        return view('musicas.index',compact('musicas'));
    }    

    /**
     * Show the form for creating a new resource.
     *
     * @return view
     */
    public function create()
    {
        $artistas = Artistas::where('status', true)
               ->orderBy('nome', 'desc')
               ->get();

        return view('musicas.create', compact('artistas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(MusicasRequest $request)
    {
        $musica = new Musicas();
        
        $musica->fill($request->all());
        $musica->save();

        $success = __('Música cadastrado com sucesso!');
        Session::flash('success',$success);

        return redirect()->route('musicas.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Musicas  $musica
     * @return \Illuminate\Http\Response
     */
    public function show(Musicas $musica)
    {
        $musica = Musicas::select('musicas.*', 'artistas.nome as artista')
            ->join('artistas','musicas.artistas_id','=', 'artistas.id')
            ->where('musicas.id', '=', $musica->id)
            ->first();

        return view('musicas.show',compact('musica'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Musicas  $musica
     * @return \Illuminate\Http\Response
     */
    public function edit(Musicas $musica)
    {
        $artistas = Artistas::where('status', true)
               ->orderBy('nome', 'desc')
               ->get();        
        return view('musicas.edit',compact('musica', 'artistas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Musicas $musica
     * @return \Illuminate\Http\Response
     */
    public function update(MusicasRequest $request, Musicas $musica)
    {
        try {
            $musica->update($request->all());

        } catch (ModelNotFoundException $e) {
            $message = __('Houve um problema ao editar a música.');
            Session::flash('error', $message);

            return redirect()->route('musicas.edit');
        }

        $message = __('Música editado com sucesso.');
        Session::flash('success', $message);

        return redirect()->route('musicas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Musicas  $musicay
     * @return \Illuminate\Http\Response
     */
    public function destroy(Musicas $musica)
    {
        try {
            $musica->delete();

        } catch (ModelNotFoundException $e) {
            $message = __('Houve um problema ao remover a música.');
            Session::flash('error', $message);

            return redirect()->route('musicas.index');
        }

        $message = __('Música removido com sucesso.');
        Session::flash('success', $message);

        return redirect()->route('musicas.index');
    }
}

resources/views/musicas/_form.blade.php
<div class="row mb-4 filters">
    <div class="col-md-4 col-12">
        <label for="nome">Nome <span class="text-danger">*</span></label>
        <input class="form-control" type="text" id="nome" maxlength="150" name="nome" value="{{@old('nome')??$musica->nome??''}}" required />
    </div>

    <div class="col-md-4 col-12">
        <label for="tipo">Artista <span class="text-danger">*</span></label>
		<select class="form-control" name="artistas_id" id="artistas_id" required>

					
			@foreach($artistas as $artista)
                @if(isset($musica) && $musica->artistas_id == $artista->id)
                    <option value="{{$artista->id}}" selected="selected">{!! $artista->nome !!}</option>
                @else
                    <option value="{{$artista->id}}">{!! $artista->nome !!}</option>
                @endif
            @endforeach


        </select>        
    </div>

    <div class="col-md-4 col-12">
        <label for="duracao">Duração <span class="text-danger">*</span></label>
        <input class="form-control" type="text" id="duracao" maxlength="150" name="duracao" placeholder="00:00:00" value="{{@old('nome')??$musica->duracao??''}}" required />
    </div>

</div>

resources/views/musicas/create.blade.php
<form role="form" id="form_musicas" action="{{route('musicas.store')}}" method="post" >
{{csrf_field()}}
@include('musicas._form')
<div class="row">
    <div class="ml-3 mt-3">
		<button type="submit">Salvar</button>
    </div>
</div>    
</form>

resources/views/musicas/edit.blade.php
<form role="form" id="form_musicas" action="{{route('musicas.update', $musica)}}" method="post" >
{{csrf_field()}}
@include('musicas._form')
<div class="row">
    <div class="ml-3 mt-3">
		<button type="submit">&nbsp;</i> Salvar</button>
    </div>
</div>    
</form>

<a href="{{ route('musicas.index') }}">Voltar</a>

resources/views/musicas/index.blade.php
<h1>Músicas</h1>

@if (Session::has('success'))
	<p>{{ Session::get('success') }}</p>
@endif
@if (Session::has('error'))
	<strong>Erro: </strong><p>{{ Session::get('error') }}</p>
@endif

<p><a href="{{ route('musicas.create') }}">Adicionar</a></p>


<table>
	<thead>
		<tr>
			<th>Nome</th>
			<th>Artista</th>
			<th>Duração</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		@foreach($musicas as $musica)
			<tr>
				<td>{{ $musica->nome }}</td>
				<td>{{ $musica->artista }}</td>
				<td>{{ $musica->duracao }}</td>
				<td>
					<a href="{{ route('musicas.show', $musica) }}">Ver</a>
					<a href="{{ route('musicas.edit', $musica) }}">Editar</a>
					<a href="{{ route('musicas.destroy', $musica) }}">Remover</a>
				</td>
			</tr>
		@endforeach
	</tbody>
</table>

<p><a href="{{ route('artistas.index') }}">Voltar</a></p>

resources/views/musicas/show.blade.php
<h1>Artistas</h1>

<table>
	<thead>
		<tr>
			<th>Nome</th>
			<th>Artista</th>
			<th>Duração</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>{{ $musica->nome }}</td>
			<td>{{ $musica->artista }}</td>
			<td>{{ $musica->duracao }}</td>
		</tr>
	</tbody>
</table>

<a href="{{ route('musicas.index') }}">Voltar</a>